
swipe:
  3:
    left:
      command: 'xdotool key alt+Shift+Tab'
    right:
      command: 'xdotool key alt+Tab'
    up:
      command: 'xdotool key super+Up'
    down:
      command: 'xdotool key super+Down'
  4:
    up:
      command: 'xdotool key super+shift+Up'
    down:
      command: 'xdotool key super+shift+Down'

pinch:
  in:
    command: 'xdotool key super+a'
    threshold: 0.1
  out:
     command: 'xdotool key super'
     threshold: 0.1


threshold:
  swipe: 1
  pinch: 1


interval:
  swipe: 1
  pinch: 1
